### PR TITLE
Expand excluded modes, add two optional features

### PR DESCRIPTION
**Pull request by jimeh**
Before discovering snap-indent, I wrote my own [`yank-indent`](https://github.com/jimeh/yank-indent) package. As such I figured I'd offer up a PR with the features from yank-indent which I find most useful, in the hopes of maybe switching my own config to snap-indent.

- Larger list of excluded modes.
- Optional yank threshold to avoid trigger indent on excessively large yanked regions.
- Optional ability to skip indent when triggering yank with a prefix arg.

Each one of these changes are in their own commits, and I'd be happy to hear/address any feedback you might have :)

### CODE REVIEW

**Comment by jimeh** [comment]
@jeffvalk any chance you might have time to look at this soon? :)

**Comment by riscy** [comment]
Hi @jeffvalk - for more context there is a PR open on MELPA here - https://github.com/melpa/melpa/pull/8496 for @jimeh's similar package, and I've asked @jimeh to see if these extra features can be made a part of your package.  (This is better for the community than having two packages that do approximately the same thing.)

**Comment by jeffvalk** [comment]
Thanks for the PR @jimeh, and thanks for grabbing my attention @riscy. I'll take a look at it this weekend, and hopefully merge the features.

**Comment by jeffvalk** [comment]
Good features, @jimeh.

I branched your PR as [ad-hoc-ignore][branch] and applied your per-command skipping and max length updates to indent on save as well as on yank. I also added a user-specified predicate for per-command skipping so users aren't limited to what we've thought of. And tests.

Your changes were pulled in 2b8000f419f24571464f78fd8538ef9f8ff004d6 and ef3bcab6535f6503d4b0812ce6acd3b184b49484. Thanks, again!

[branch]: https://github.com/jeffvalk/snap-indent/commits/ad-hoc-ignore

**Pull request closed without merging**
